# Generated by Django 4.2.2 on 2023-07-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '멤버', 'verbose_name_plural': '멤버'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=128, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=16, unique=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pw',
            field=models.CharField(max_length=128, verbose_name='비밀번호'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Members',
        ),
    ]
