# Generated by Django 4.2.2 on 2023-07-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_author_comment_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
