# Generated by Django 4.2.2 on 2023-07-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_comment_author_id_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=48, verbose_name='글 제목'),
        ),
    ]
