# Generated by Django 4.2.2 on 2023-07-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_comment_options_comment_parent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
