# Generated by Django 4.2.2 on 2023-07-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_reply_parent_alter_reply_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='reply',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
