# Generated by Django 4.2.2 on 2023-07-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_table'),
        ('board', '0013_alter_reply_options_reply_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_boards', to='user.user'),
        ),
    ]
